services:
  api:
    image: samuell19/projeetotcc:api-latest
    build:
      context: .
      dockerfile: apps/api/Dockerfile

  web:
    image: samuell19/projeetotcc:web-latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
